### ISSUE TITLE
Errors are not passed through

### ISSUE THREAD

**Issue by vpzomtrrfrt** [benjamingr/tmp-promise#34]
This snippet attempts to create a temp file in a directory that doesn't exist.
```
const tmp = require("tmp-promise");
tmp.file({dir: "nonexistent"})
	.then(console.log);
```
But instead of an error indicating that, it returns this:
```
internal/util.js:214
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:214:11)
    at tmp.file (/home/colin/tmptest/node_modules/tmp-promise/index.js:9:61)
    at _fileCreated (/home/colin/tmptest/node_modules/tmp/lib/tmp.js:252:23)
```

**Comment by benjamingr** [comment]
Published in 2.0.2, thanks for the report! Thanks for the quick fix @paulmelnikow !
